name: Auto Assign Issue Metadata

on:
  issues:
    types: [opened]

jobs:
  add_metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project and set status
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/orgs/OpenPecha/projects/78
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          # Set the status column/field name & value
          status: "USER FEEDBACK"
