name: Auto Assign Issue Metadata

on:
  issues:
    types: [opened]

jobs:
  add_metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project and set status
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/orgs/OpenPecha/projects/12
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Add labels to new issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          script: |
              const labels = ["user-feedback", "buddhistai tools"];
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labels
              });
